### ISSUE TITLE
Unable to run, following the Readme

### ISSUE THREAD

**Issue by davidlstanton** [jeremyber-aws/local-development-with-flink-and-kinesis#1]
When I follow the Readme and try to run I get the following errors:

Error: Unable to initialize main class myflinkapp.Kinesis_StreamingJob
Caused by: java.lang.NoClassDefFoundError: org/apache/flink/api/common/serialization/DeserializationSchema

Any thoughts?

**Comment by jeremyber-aws** [comment]
You may need to check the box in your IntelliJ IDE Run Configuration to Include Dependencies with Provided Scope.

Apologies for not including in the instructions. Once you confirm this works I will add it.


![run-provided](https://user-images.githubusercontent.com/74626212/179998604-8e1fff38-fb45-468c-915a-8b10b0e162d8.png)

**Comment by davidlstanton** [comment]
Cheers for really fast reply :-)
this worked.

I also had to set JRE to Java 11 from the default.
